import React, { createContext, useContext, useState, useCallback } from 'react';
import type { ReactNode } from 'react';

export type Lang = 'fr' | 'en';

const STORAGE_KEY = 'vintia_lang';

// ── Traductions ────────────────────────────────────────────────────────────
export const translations = {
  fr: {
    // TopBar
    topBarTitle: 'Vos Ventes',

    // HelpButton
    startTutorial: 'Démarrer le tutoriel',
    reviewTutorial: 'Revoir le tutoriel',

    // LanguageButton
    switchLang: 'Switch to English',

    // SideNav
    allItems: 'Tout',
    allItemsTooltip: 'Afficher tous les articles, toutes plateformes confondues',
    addPlatform: 'Ajouter',
    addPlatformTooltip: 'Connecter une nouvelle plateforme de vente',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    itemCount: (n: number) => `${n} ligne${n !== 1 ? 's' : ''}`,
    platformTooltip: (label: string, url: string, count: number) =>
      `${label}${url ? ` — ${url.replace('https://', '')}` : ''} · ${count} ligne${count !== 1 ? 's' : ''}`,

    // MainContent — StatsBar
    statsArticles: 'Articles',
    statsAchats: 'Achats',
    statsVentes: 'Ventes',
    statsAttente: 'En attente',
    statsVendus: 'Vendus',
    statsCA: "Chiffre d'aff.",
    statsTotalAchats: 'Total achats',
    statsMarge: 'Marge',
    statsTipArticles: 'Articles actifs (hors perdus)',
    statsTipAchats: 'Articles achat (−)',
    statsTipVentes: 'Articles vente (+)',
    statsTipAttente: 'Articles en étude (?)',
    statsTipVendus: 'Articles avec prix vendu',
    statsTipCA: "Chiffre d'affaires",
    statsTipTotalAchats: 'Total des achats',
    statsTipMarge: 'Marge nette = CA − Achats',
    // Mobile labels
    statsMobileAchetes: 'Achetés',
    statsMobileVendus: 'Vendus',
    statsMobileCA: 'CA',
    statsMobileAchatsEur: 'Achats €',
    statsMobileMarge: 'Marge',
    statsMobileTipAchetes: 'Articles achetés (−)',
    statsMobileTipVendus: 'Articles mis en vente (+)',

    // MainContent — AIHeader
    aiDailyReco: 'Recommandation IA du jour',
    aiRecoTooltip: "Recommandation IA générée à partir de vos données réelles, renouvelée chaque jour à 10h00",
    aiGeneratedAt: (d: string) => `Généré le ${d}`,
    aiRefreshTooltip: 'Régénérer maintenant (efface le cache)',
    aiAnalyzing: 'Analyse…',
    aiRefresh: 'Actualiser',
    aiNoKeyError: "Clé API non configurée — ajoutez-la dans Paramètres pour activer la recommandation.",
    aiNoReco: 'Aucune recommandation — configurez une clé IA dans les Paramètres.',

    // SettingsPanel
    settingsTitle: 'Paramètres',
    settingsBackTooltip: 'Retourner au tableau des articles',
    settingsSectionProfile: 'Profil',
    settingsFullName: 'Nom complet',
    settingsFullNamePlaceholder: 'Prénom Nom',
    settingsAvatarUrl: 'Photo de profil (URL)',
    settingsAvatarUrlTooltip: "URL d'une image en ligne pour votre photo",
    settingsAvatarUrlPlaceholder: 'https://exemple.com/photo.jpg',
    settingsSectionAI: 'IA & Recherche web',
    settingsAIInfo: "Choisissez votre IA préférée pour analyser vos articles et rechercher les prix du marché. La clé API est stockée uniquement sur cet appareil.",
    settingsAIProvider: "Fournisseur d'IA",
    settingsAIModel: 'Modèle',
    settingsAIModelTooltip: (label: string) => `Modèle ${label} à utiliser`,
    settingsAPIKey: (label: string) => `Clé API ${label}`,
    settingsAPIKeyTooltip: (label: string, hint: string) => `Clé API ${label} — disponible sur ${hint}`,
    settingsAPIKeyConfigured: (label: string) => `Clé ${label} configurée`,
    settingsWebSearchEnabled: 'Recherche web activée',
    settingsNoKey: "Aucune clé — les analyses ne fonctionneront pas",
    settingsSectionFallback: 'IA de secours (fallback)',
    settingsFallbackInfo: "Si l'IA principale ne peut pas accéder au site, Vintia essaie automatiquement ces IA de secours (dans l'ordre). Maximum 2 fallbacks.",
    settingsFallbackLabel: (n: number) => `Fallback ${n}`,
    settingsFallbackConfigured: (label: string) => `${label} configuré`,
    settingsFallbackProvider: 'Fournisseur',
    settingsFallbackModel: 'Modèle',
    settingsFallbackApiKey: (label: string) => `Clé API ${label}`,
    settingsFallbackApiKeyTooltip: (label: string, hint: string) => `Clé API ${label} — ${hint}`,
    settingsSectionAccount: 'Compte',
    settingsDeleteAccount: 'Supprimer mon compte',
    settingsDeleteAccountDesc: 'Supprime définitivement votre compte et toutes vos données.',
    settingsDelete: 'Supprimer',
    settingsSave: 'Sauvegarder',
    settingsSaved: 'Sauvegardé !',
    settingsDeleteModalTitle: 'Supprimer mon compte',
    settingsDeleteModalDesc: 'Cette action est <strong>irréversible</strong>. Toutes vos données (articles, plateformes, paramètres) seront définitivement supprimées.',
    settingsDeleteModalLabel: 'Tapez',
    settingsDeleteModalWord: 'SUPPRIMER',
    settingsDeleteModalWordFull: 'SUPPRIMER',
    settingsDeleteModalConfirm: 'pour confirmer',
    settingsDeleteModalCancel: 'Annuler',
    settingsDeleteModalConfirmBtn: 'Supprimer définitivement',
    settingsDeleteModalDeleting: 'Suppression...',

    // ConnectPlatformModal
    connectTitle: 'Connecter un site',
    connectSubtitle: 'Choisissez une plateforme ou ajoutez la vôtre',
    connectTabPreset: 'Sites prédéfinis',
    connectTabCustom: 'Site personnalisé',
    connectCustomName: 'Nom du site *',
    connectCustomNamePlaceholder: 'Ex: Depop, Vestiaire...',
    connectCustomUrl: 'URL du site',
    connectCustomColor: 'Couleur',
    connectCustomAdd: 'Ajouter ce site',

    // PlatformEditModal
    platformEditTitle: 'Modifier la plateforme',
    platformEditName: 'Nom *',
    platformEditNamePlaceholder: 'Ex: Vinted, Leboncoin...',
    platformEditUrl: 'URL du site',
    platformEditColor: 'Couleur',
    platformEditIcon: 'Icône',
    platformEditDelete: 'Supprimer',
    platformEditCancel: 'Annuler',
    platformEditSave: 'Enregistrer',
    platformEditConfirmDelete: 'Confirmer la suppression ?',

    // PerplexityModal
    perplexityAnalyzing: (provider: string) => `Analyse ${provider} en cours...`,
    perplexityReport: 'Rapport IA',
    perplexityClose: 'Fermer',
    perplexityApply: 'Appliquer à la ligne',
    perplexityNoResult: 'Aucun résultat disponible.',
    perplexitySavedReport: 'Rapport sauvegardé',
    perplexityAnalyzeLabel: 'Analyse IA',
    perplexityObject: 'Objet',
    perplexityViewListing: "Voir l'annonce",
    perplexityDisplayedPrice: 'Prix affiché',
    perplexityBuyPrice: 'Achat conseillé',
    perplexitySellPrice: 'Proposition vente',
    perplexityMarketRange: 'Fourchette marché',
    perplexityPotentialMargin: 'Marge potentielle',
    perplexityTips: 'Conseils',
    perplexitySimilarItems: 'Articles similaires',
    perplexitySources: 'Sources',
    perplexityAnalyzeSection: 'Analyse',
    perplexityAnalyzedBy: (p: string) => `Analysé par ${p}`,
    perplexityVia: (p: string) => `Via ${p}`,
    perplexityLoading: 'Analyse en cours…',
    perplexityErrorTitle: "Erreur d'analyse",
    perplexityAccessError: (provider: string) => `Accès au site impossible${provider ? ` (${provider})` : ''}. Prix basés sur des estimations.`,
    perplexityFallbackMsg: (provider: string) => `Analyse via ${provider} (l'IA principale n'a pas pu accéder au site).`,
    perplexityScoreGood: 'Recommandé',
    perplexityScoreOk: 'Acceptable',
    perplexityScoreBad: 'Déconseillé',

    // AuthScreen
    authWelcomeTagline: 'Votre gestionnaire de revente intelligent',
    authStep1Title: 'Connectez vos plateformes',
    authStep1Desc: 'Vinted, Leboncoin, eBay… ajoutez vos plateformes de revente.',
    authStep2Title: 'Ajoutez vos articles',
    authStep2Desc: 'Enregistrez achats, ventes et articles en attente en quelques secondes.',
    authStep3Title: "Laissez l'IA travailler",
    authStep3Desc: 'Analyse de marché, prix conseillés et recommandation quotidienne générés automatiquement.',
    authStep4Title: 'Optimisez vos marges',
    authStep4Desc: 'Comparez, ajustez vos prix et suivez vos gains en temps réel.',
    authCreateAccount: 'Créer mon compte gratuitement',
    authAlreadyAccount: 'J\'ai déjà un compte — Se connecter',
    authBack: 'Retour',
    authLoginTitle: 'Se connecter',
    authLoginSubtitle: 'Accédez à votre espace Vintia',
    authEmail: 'Adresse e-mail',
    authPassword: 'Mot de passe',
    authLogin: 'Se connecter',
    authLoggingIn: 'Connexion...',
    authNoAccount: 'Pas encore de compte ?',
    authCreateAccountLink: 'Créer un compte',
    authLoginError: 'Email ou mot de passe incorrect.',
    authRegisterTitle: 'Créer un compte',
    authRegisterSubtitle: 'Gérez vos ventes sur toutes vos plateformes',
    authFullName: 'Votre prénom et nom',
    authConfirmPassword: 'Confirmer le mot de passe',
    authRegister: 'Créer mon compte',
    authRegistering: 'Création...',
    authHasAccount: 'Déjà un compte ?',
    authLoginLink: 'Se connecter',
    authNameRequired: 'Le nom est requis',
    authInvalidEmail: 'Adresse e-mail invalide',
    authPasswordTooShort: 'Mot de passe trop court (8 caractères min)',
    authPasswordMismatch: 'Les mots de passe ne correspondent pas',
    authEmailExists: 'Un compte existe déjà avec cet e-mail.',
    authCheckEmail: 'Vérifie ta boîte mail pour confirmer ton compte.',
    // Password strength
    authPwChars: '8+ caractères',
    authPwUpper: 'Majuscule',
    authPwDigit: 'Chiffre',
    authPwSpecial: 'Caractère spécial',
    authPwWeak0: 'Très faible',
    authPwWeak1: 'Faible',
    authPwWeak2: 'Moyen',
    authPwWeak3: 'Fort',

    // ItemTable
    tableAddItem: 'Ajouter un article',
    tableNoItems: 'Aucun article pour l\'instant',
    tableNoItemsHint: 'Cliquez sur "Ajouter un article" pour commencer.',
    tableColTransaction: 'Statut',
    tableColType: 'Catégorie',
    tableColTitle: 'Article',
    tableColUrl: 'Lien',
    tableColPrices: 'Prix',
    tableColCompare: 'Comparer',
    tableColIA: 'IA',
    tableColActions: 'Actions',
    tableFilterAll: 'Tout',
    tableFilterClear: 'Tout effacer',

    // InlineRow
    rowEdit: 'Modifier',
    rowDelete: 'Supprimer',
    rowSave: 'Enregistrer',
    rowCancel: 'Annuler',
    rowDeleteConfirm: 'Confirmer',
    rowDeleteCancel: 'Non',
    rowAIAnalyze: 'Analyser avec l\'IA',
    rowAIReport: 'Voir le rapport IA',
    rowCompare: 'Comparer',
    rowOpenUrl: 'Voir l\'annonce',
    rowDescription: 'Description',
    rowComment: 'Note',
    rowTitlePlaceholder: 'Titre de l\'article',
    rowUrlPlaceholder: 'https://...',
    rowDescPlaceholder: 'Description pour l\'IA...',
    rowCommentPlaceholder: 'Note personnelle...',
    rowPlatform: 'Plateforme',
    rowNoPlatform: 'Aucune',
    rowPriceAchat: 'Achat',
    rowPriceVente: 'Proposition',
    rowPriceVendu: 'Vente',
    rowMarge: 'Marge',
    rowLinkedItems: (n: number) => `${n} lié${n > 1 ? 's' : ''}`,
    rowNoLinkedItems: 'Aucun',
    rowCompareWith: 'Comparer avec',
    rowCompareSelect: 'Sélectionner des articles à comparer',
    rowDateAdded: (d: string) => d,
    rowPriceTarget: 'Prix cible IA',
    rowRecommendation: 'Recommandation',
    rowIABuy: 'IA Achat',
    rowIAProp: 'IA Prop.',
    rowUntitled: 'Sans titre',
    rowNoOtherItem: 'Aucun autre article',
    rowNoDescEmpty: "Aucune description — double-cliquez pour en ajouter une (aide l'IA si le site est inaccessible).",
    rowDescHide: 'Masquer la description',
    rowDescShow: 'Voir la description',
    rowDescAdd: "Ajouter une description (aide l'IA si le site est inaccessible)",
    rowLink: 'Lien :',
    rowDblClickToEdit: 'Double-clic pour modifier',
    rowEditUrl: (url: string) => `Modifier : ${url}`,
    rowIATooltip: 'Prix IA cible + recommandation pour optimiser votre vente',
    rowIACommentTooltip: 'Cliquez pour voir le commentaire IA',
    rowCompareCellTooltip: 'Comparaison — articles liés pour comparer les prix',
    rowSaveTooltip: 'Enregistrer (Entrée)',
    rowCancelTooltip: 'Annuler (Echap)',
    rowReportTooltip: "Voir le dernier rapport d'analyse IA",
    rowNewAnalysisTooltip: 'Lancer une nouvelle analyse IA — prix du marché, demande, conseils',
    rowEditTooltip: 'Modifier (ou double-cliquez sur la ligne)',
    rowDeleteTooltip: 'Supprimer cet article',
    rowDeleteConfirmTooltip: 'Confirmer la suppression définitive',
    rowDeleteCancelTooltip: 'Annuler la suppression',
    rowPerplexityTooltip: 'Rechercher sur le web avec Perplexity — prix du marché, demande, conseils',
    rowAIAnalyzeTooltip: "Analyser avec l'IA — obtenir un prix cible et une recommandation",
    rowDescPlaceholderFull: "Décrivez l'article (état, taille, marque, défauts...) — utilisé par l'IA si l'annonce est inaccessible",
    rowDescLabelIcon: 'Description :',

    // Transaction labels
    transactionAchat: 'Achat',
    transactionVente: 'Vente',
    transactionAttente: 'En attente',
    transactionPerdu: 'Perdu',
    transactionTooltipAchat: "Achat — vous avez dépensé de l'argent pour acquérir cet article",
    transactionTooltipVente: 'Vente — vous avez vendu ou vous mettez en vente cet article',
    transactionTooltipAttente: "En attente — vous étudiez cet article avant de décider de l'acheter ou non",
    transactionTooltipPerdu: "Perdu — cet article en attente a été vendu à quelqu'un d'autre",

    // Type labels
    typeVetement: 'Vêtement',
    typeChaussures: 'Chaussures',
    typeAccessoires: 'Accessoires',
    typeElectronique: 'Électronique',
    typeInformatique: 'Informatique',
    typeMaison: 'Maison',
    typeDecoration: 'Décoration',
    typeSport: 'Sport',
    typeLoisirs: 'Loisirs',
    typeLivres: 'Livres',
    typeJouets: 'Jouets',
    typeCosmetique: 'Cosmétique',
    typeAlimentation: 'Alimentation',
    typeBusiness: 'Business',
    typeAutre: 'Autre',
    typeTooltipVetement: 'Vêtement — habits, manteaux, pulls...',
    typeTooltipChaussures: 'Chaussures — baskets, bottes, sandales...',
    typeTooltipAccessoires: 'Accessoires — sacs, ceintures, bijoux...',
    typeTooltipElectronique: 'Électronique — audio, photo, télévision...',
    typeTooltipInformatique: 'Informatique — ordinateurs, périphériques...',
    typeTooltipMaison: 'Maison — mobilier, cuisine, rangement...',
    typeTooltipDecoration: 'Décoration — cadres, vases, plantes...',
    typeTooltipSport: 'Sport — équipements, vêtements sportifs...',
    typeTooltipLoisirs: 'Loisirs — jeux, instruments, collections...',
    typeTooltipLivres: 'Livres — romans, BD, manuels, magazines...',
    typeTooltipJouets: 'Jouets — enfants, figurines, jeux de société...',
    typeTooltipCosmetique: 'Cosmétique — parfums, soins, maquillage...',
    typeTooltipAlimentation: 'Alimentation — produits alimentaires, boissons...',
    typeTooltipBusiness: 'Business — articles suivis pour la performance commerciale',
    typeTooltipAutre: 'Autre — catégorie non listée',

    // Tutorial mock items
    tutorialItem1Title: 'iPhone 13 Pro — 256 Go',
    tutorialItem1Desc: "Très bon état, boîte d'origine, chargeur inclus.",
    tutorialItem1Reco: 'Baisser légèrement le prix pour accélérer la vente.',
    tutorialItem1Insight: 'Les iPhone 13 Pro se vendent bien entre 420 € et 500 €.',
    tutorialItem2Title: 'Samsung Galaxy S22 — 128 Go',
    tutorialItem2Desc: 'Reconditionné grade A, batterie 95%.',

    // Tutorial overlay
    tutorialLocale: { skip: 'Passer', next: 'Suivant', back: 'Retour', close: 'Fermer', last: 'Terminer' },
    tutorialWelcomeTitle: 'Bienvenue sur Vintia 🎉',
    tutorialWelcomeBody: "Je vais vous guider à travers les principales fonctionnalités. Deux articles d'exemple ont été ajoutés pour illustrer le tutoriel.",
    tutorialAllTitle: 'Vue globale',
    tutorialAllBody: "Cliquez ici pour afficher tous vos articles, quelle que soit la plateforme. C'est votre vue d'ensemble.",
    tutorialAddPlatTitle: 'Ajouter une plateforme',
    tutorialAddPlatBody: 'Connectez Vinted, Leboncoin, eBay ou autres pour synchroniser vos ventes. Vous pouvez les réorganiser par glisser-déposer.',
    tutorialRecoTitle: 'Recommandation IA du jour',
    tutorialRecoBody: 'Votre IA analyse connectée à vos données vous propose chaque jour des conseils personnalisés. Cliquez sur "Actualiser" pour régénérer l\'analyse.',
    tutorialStatsTitle: "Vos chiffres en un coup d'œil",
    tutorialStatsBody: 'Ce bandeau résume votre activité en temps réel :',
    tutorialStatsArticles: 'Articles',
    tutorialStatsArticlesDesc: 'total actifs',
    tutorialStatsAchats: 'Achats',
    tutorialStatsAchatsDesc: 'articles achetés (−)',
    tutorialStatsVentes: 'Ventes',
    tutorialStatsVentesDesc: 'mis en vente (+)',
    tutorialStatsAttente: 'En attente',
    tutorialStatsAttenteDesc: "en cours d'étude",
    tutorialStatsCA: 'CA',
    tutorialStatsCADesc: "chiffre d'affaires réalisé",
    tutorialStatsTotalAchats: 'Total achats',
    tutorialStatsTotalAchatsDesc: 'dépenses cumulées',
    tutorialStatsMarge: 'Marge',
    tutorialStatsMargeDesc: 'CA − Achats',
    tutorialPricesTitle: "Les trois prix d'un article",
    tutorialPricesAchat: 'Achat',
    tutorialPricesAchatDesc: "prix payé pour acquérir l'objet",
    tutorialPricesPropo: 'Proposition',
    tutorialPricesPropoDesc: 'prix affiché sur votre annonce',
    tutorialPricesVente: 'Vente',
    tutorialPricesVenteDesc: 'prix réellement encaissé à la vente',
    tutorialPricesNote: 'La marge se calcule automatiquement : Vente − Achat.',
    tutorialAddItemTitle: 'Ajouter un article',
    tutorialAddItemBody: "Cliquez ici pour créer un nouvel article. Une ligne de saisie apparaît directement dans le tableau.",
    tutorialAddItemNote: "Renseignez le titre, le prix d'achat et le prix de proposition. Plus la fiche est complète, plus l'analyse IA sera précise.",
    tutorialIAColTitle: 'Colonne IA',
    tutorialIAColBody: "Affiche le prix cible suggéré par l'IA et une recommandation courte (baisser, maintenir, relancer...). Elle se remplit après une analyse sur cet article.",
    tutorialAnalyzeTitle: 'Analyse marché',
    tutorialAnalyzeBody: "Lance une analyse IA sur cet article : prix moyens constatés sur le marché, niveau de demande, tendances et conseils de prix personnalisés.",
    tutorialAnalyzeNote: 'Nécessite une clé API configurée dans les Paramètres.',
    tutorialReportTitle: 'Rapport IA complet',
    tutorialReportBody: "Après une analyse, ce bouton donne accès au rapport détaillé : fourchette de prix, popularité, conseils de mise en valeur et estimation de délai de vente.",
    tutorialReportNote: "L'article exemple a déjà un rapport — essayez en cliquant dessus !",
    tutorialCompareTitle: 'Comparer des articles',
    tutorialCompareBody: "Liez plusieurs articles entre eux pour les comparer côte à côte — utile pour ajuster vos prix quand vous avez des objets similaires sur plusieurs plateformes.",
    tutorialCompareNote: "Le chiffre indique le nombre d'articles liés. Les deux articles exemples sont déjà liés entre eux.",
    tutorialEditTitle: 'Modifier un article',
    tutorialEditBody: "Double-cliquez sur n'importe quelle ligne ou utilisez ce bouton pour modifier un article directement dans le tableau.",
    tutorialDeleteTitle: 'Supprimer',
    tutorialDeleteBody: "Supprimez un article après confirmation. Attention, cette action est irréversible.",
    tutorialSettingsTitle: 'Paramètres & Profil',
    tutorialSettingsBody: "Accédez à votre profil, configurez vos clés API IA et gérez vos préférences.",
    tutorialLogoutTitle: 'Déconnexion',
    tutorialLogoutBody: "Déconnectez-vous de votre compte. Vos données restent sauvegardées.",
    tutorialEndTitle: 'Vous êtes prêt ! 🚀',
    tutorialEndBody: "Les articles d'exemple ont été supprimés. Vous pouvez relancer ce tutoriel à tout moment via le bouton d'aide en haut à droite.",
  },

  en: {
    // TopBar
    topBarTitle: 'Your Sales',

    // HelpButton
    startTutorial: 'Start tutorial',
    reviewTutorial: 'Review tutorial',

    // LanguageButton
    switchLang: 'Passer en français',

    // SideNav
    allItems: 'All',
    allItemsTooltip: 'Show all items across all platforms',
    addPlatform: 'Add',
    addPlatformTooltip: 'Connect a new selling platform',
    settings: 'Settings',
    logout: 'Logout',
    itemCount: (n: number) => `${n} row${n !== 1 ? 's' : ''}`,
    platformTooltip: (label: string, url: string, count: number) =>
      `${label}${url ? ` — ${url.replace('https://', '')}` : ''} · ${count} row${count !== 1 ? 's' : ''}`,

    // MainContent — StatsBar
    statsArticles: 'Items',
    statsAchats: 'Purchases',
    statsVentes: 'Sales',
    statsAttente: 'Pending',
    statsVendus: 'Sold',
    statsCA: 'Revenue',
    statsTotalAchats: 'Total spent',
    statsMarge: 'Margin',
    statsTipArticles: 'Active items (excluding lost)',
    statsTipAchats: 'Purchase items (−)',
    statsTipVentes: 'Sale items (+)',
    statsTipAttente: 'Items under review (?)',
    statsTipVendus: 'Items with sale price',
    statsTipCA: 'Revenue',
    statsTipTotalAchats: 'Total purchases',
    statsTipMarge: 'Net margin = Revenue − Purchases',
    // Mobile labels
    statsMobileAchetes: 'Bought',
    statsMobileVendus: 'Sold',
    statsMobileCA: 'Rev.',
    statsMobileAchatsEur: 'Spent €',
    statsMobileMarge: 'Margin',
    statsMobileTipAchetes: 'Items bought (−)',
    statsMobileTipVendus: 'Items listed for sale (+)',

    // MainContent — AIHeader
    aiDailyReco: 'AI Recommendation of the Day',
    aiRecoTooltip: 'AI recommendation generated from your real data, renewed every day at 10:00',
    aiGeneratedAt: (d: string) => `Generated on ${d}`,
    aiRefreshTooltip: 'Regenerate now (clears cache)',
    aiAnalyzing: 'Analyzing…',
    aiRefresh: 'Refresh',
    aiNoKeyError: 'API key not configured — add it in Settings to enable recommendations.',
    aiNoReco: 'No recommendation — configure an AI key in Settings.',

    // SettingsPanel
    settingsTitle: 'Settings',
    settingsBackTooltip: 'Back to item table',
    settingsSectionProfile: 'Profile',
    settingsFullName: 'Full name',
    settingsFullNamePlaceholder: 'First Last',
    settingsAvatarUrl: 'Profile photo (URL)',
    settingsAvatarUrlTooltip: 'URL of an online image for your photo',
    settingsAvatarUrlPlaceholder: 'https://example.com/photo.jpg',
    settingsSectionAI: 'AI & Web Search',
    settingsAIInfo: 'Choose your preferred AI to analyze your items and search market prices. The API key is stored only on this device.',
    settingsAIProvider: 'AI Provider',
    settingsAIModel: 'Model',
    settingsAIModelTooltip: (label: string) => `${label} model to use`,
    settingsAPIKey: (label: string) => `${label} API Key`,
    settingsAPIKeyTooltip: (label: string, hint: string) => `${label} API key — available at ${hint}`,
    settingsAPIKeyConfigured: (label: string) => `${label} key configured`,
    settingsWebSearchEnabled: 'Web search enabled',
    settingsNoKey: 'No key — analyses will not work',
    settingsSectionFallback: 'Fallback AI',
    settingsFallbackInfo: "If the main AI can't access a site, Vintia automatically tries these fallback AIs (in order). Maximum 2 fallbacks.",
    settingsFallbackLabel: (n: number) => `Fallback ${n}`,
    settingsFallbackConfigured: (label: string) => `${label} configured`,
    settingsFallbackProvider: 'Provider',
    settingsFallbackModel: 'Model',
    settingsFallbackApiKey: (label: string) => `${label} API Key`,
    settingsFallbackApiKeyTooltip: (label: string, hint: string) => `${label} API key — ${hint}`,
    settingsSectionAccount: 'Account',
    settingsDeleteAccount: 'Delete my account',
    settingsDeleteAccountDesc: 'Permanently deletes your account and all your data.',
    settingsDelete: 'Delete',
    settingsSave: 'Save',
    settingsSaved: 'Saved!',
    settingsDeleteModalTitle: 'Delete my account',
    settingsDeleteModalDesc: 'This action is <strong>irreversible</strong>. All your data (items, platforms, settings) will be permanently deleted.',
    settingsDeleteModalLabel: 'Type',
    settingsDeleteModalWord: 'DELETE',
    settingsDeleteModalWordFull: 'DELETE',
    settingsDeleteModalConfirm: 'to confirm',
    settingsDeleteModalCancel: 'Cancel',
    settingsDeleteModalConfirmBtn: 'Delete permanently',
    settingsDeleteModalDeleting: 'Deleting...',

    // ConnectPlatformModal
    connectTitle: 'Connect a site',
    connectSubtitle: 'Choose a platform or add your own',
    connectTabPreset: 'Preset sites',
    connectTabCustom: 'Custom site',
    connectCustomName: 'Site name *',
    connectCustomNamePlaceholder: 'E.g.: Depop, Vestiaire...',
    connectCustomUrl: 'Site URL',
    connectCustomColor: 'Color',
    connectCustomAdd: 'Add this site',

    // PlatformEditModal
    platformEditTitle: 'Edit platform',
    platformEditName: 'Name *',
    platformEditNamePlaceholder: 'E.g.: Vinted, eBay...',
    platformEditUrl: 'Site URL',
    platformEditColor: 'Color',
    platformEditIcon: 'Icon',
    platformEditDelete: 'Delete',
    platformEditCancel: 'Cancel',
    platformEditSave: 'Save',
    platformEditConfirmDelete: 'Confirm deletion?',

    // PerplexityModal
    perplexityAnalyzing: (provider: string) => `${provider} analysis in progress...`,
    perplexityReport: 'AI Report',
    perplexityClose: 'Close',
    perplexityApply: 'Apply to row',
    perplexityNoResult: 'No result available.',
    perplexitySavedReport: 'Saved report',
    perplexityAnalyzeLabel: 'AI Analysis',
    perplexityObject: 'Item',
    perplexityViewListing: 'View listing',
    perplexityDisplayedPrice: 'Listed price',
    perplexityBuyPrice: 'Suggested buy',
    perplexitySellPrice: 'Sell price',
    perplexityMarketRange: 'Market range',
    perplexityPotentialMargin: 'Potential margin',
    perplexityTips: 'Tips',
    perplexitySimilarItems: 'Similar items',
    perplexitySources: 'Sources',
    perplexityAnalyzeSection: 'Analysis',
    perplexityAnalyzedBy: (p: string) => `Analysed by ${p}`,
    perplexityVia: (p: string) => `Via ${p}`,
    perplexityLoading: 'Analysis in progress…',
    perplexityErrorTitle: 'Analysis error',
    perplexityAccessError: (provider: string) => `Site access failed${provider ? ` (${provider})` : ''}. Prices based on estimates.`,
    perplexityFallbackMsg: (provider: string) => `Analysis via ${provider} (the main AI could not access the site).`,
    perplexityScoreGood: 'Recommended',
    perplexityScoreOk: 'Acceptable',
    perplexityScoreBad: 'Not recommended',

    // AuthScreen
    authWelcomeTagline: 'Your smart resale manager',
    authStep1Title: 'Connect your platforms',
    authStep1Desc: 'Vinted, Leboncoin, eBay… add your selling platforms.',
    authStep2Title: 'Add your items',
    authStep2Desc: 'Log purchases, sales and pending items in seconds.',
    authStep3Title: 'Let the AI work',
    authStep3Desc: 'Market analysis, suggested prices and daily recommendation generated automatically.',
    authStep4Title: 'Optimize your margins',
    authStep4Desc: 'Compare, adjust prices and track your earnings in real time.',
    authCreateAccount: 'Create my free account',
    authAlreadyAccount: 'I already have an account — Sign in',
    authBack: 'Back',
    authLoginTitle: 'Sign in',
    authLoginSubtitle: 'Access your Vintia workspace',
    authEmail: 'Email address',
    authPassword: 'Password',
    authLogin: 'Sign in',
    authLoggingIn: 'Signing in...',
    authNoAccount: 'No account yet?',
    authCreateAccountLink: 'Create an account',
    authLoginError: 'Incorrect email or password.',
    authRegisterTitle: 'Create an account',
    authRegisterSubtitle: 'Manage your sales across all your platforms',
    authFullName: 'Your full name',
    authConfirmPassword: 'Confirm password',
    authRegister: 'Create my account',
    authRegistering: 'Creating...',
    authHasAccount: 'Already have an account?',
    authLoginLink: 'Sign in',
    authNameRequired: 'Name is required',
    authInvalidEmail: 'Invalid email address',
    authPasswordTooShort: 'Password too short (8 characters min)',
    authPasswordMismatch: 'Passwords do not match',
    authEmailExists: 'An account already exists with this email.',
    authCheckEmail: 'Check your inbox to confirm your account.',
    // Password strength
    authPwChars: '8+ chars',
    authPwUpper: 'Uppercase',
    authPwDigit: 'Number',
    authPwSpecial: 'Special char',
    authPwWeak0: 'Very weak',
    authPwWeak1: 'Weak',
    authPwWeak2: 'Medium',
    authPwWeak3: 'Strong',

    // ItemTable
    tableAddItem: 'Add item',
    tableNoItems: 'No items yet',
    tableNoItemsHint: 'Click "Add item" to get started.',
    tableColTransaction: 'Status',
    tableColType: 'Category',
    tableColTitle: 'Item',
    tableColUrl: 'Link',
    tableColPrices: 'Prices',
    tableColCompare: 'Compare',
    tableColIA: 'AI',
    tableColActions: 'Actions',
    tableFilterAll: 'All',
    tableFilterClear: 'Clear all',

    // InlineRow
    rowEdit: 'Edit',
    rowDelete: 'Delete',
    rowSave: 'Save',
    rowCancel: 'Cancel',
    rowDeleteConfirm: 'Confirm',
    rowDeleteCancel: 'No',
    rowAIAnalyze: 'Analyze with AI',
    rowAIReport: 'View AI report',
    rowCompare: 'Compare',
    rowOpenUrl: 'View listing',
    rowDescription: 'Description',
    rowComment: 'Note',
    rowTitlePlaceholder: 'Item title',
    rowUrlPlaceholder: 'https://...',
    rowDescPlaceholder: 'Description for AI...',
    rowCommentPlaceholder: 'Personal note...',
    rowPlatform: 'Platform',
    rowNoPlatform: 'None',
    rowPriceAchat: 'Purchase',
    rowPriceVente: 'Listed',
    rowPriceVendu: 'Sold',
    rowMarge: 'Margin',
    rowLinkedItems: (n: number) => `${n} linked`,
    rowNoLinkedItems: 'None',
    rowCompareWith: 'Compare with',
    rowCompareSelect: 'Select items to compare',
    rowDateAdded: (d: string) => d,
    rowPriceTarget: 'AI target price',
    rowRecommendation: 'Recommendation',
    rowIABuy: 'AI Buy',
    rowIAProp: 'AI List.',
    rowUntitled: 'Untitled',
    rowNoOtherItem: 'No other items',
    rowNoDescEmpty: 'No description — double-click to add one (helps AI when the listing is inaccessible).',
    rowDescHide: 'Hide description',
    rowDescShow: 'View description',
    rowDescAdd: 'Add a description (helps AI when the listing is inaccessible)',
    rowLink: 'Link:',
    rowDblClickToEdit: 'Double-click to edit',
    rowEditUrl: (url: string) => `Edit: ${url}`,
    rowIATooltip: 'AI target price + recommendation to optimise your sale',
    rowIACommentTooltip: 'Click to view AI comment',
    rowCompareCellTooltip: 'Comparison — linked items to compare prices',
    rowSaveTooltip: 'Save (Enter)',
    rowCancelTooltip: 'Cancel (Esc)',
    rowReportTooltip: 'View last AI analysis report',
    rowNewAnalysisTooltip: 'Run a new AI analysis — market price, demand, tips',
    rowEditTooltip: 'Edit (or double-click the row)',
    rowDeleteTooltip: 'Delete this item',
    rowDeleteConfirmTooltip: 'Confirm permanent deletion',
    rowDeleteCancelTooltip: 'Cancel deletion',
    rowPerplexityTooltip: 'Search the web with Perplexity — market price, demand, tips',
    rowAIAnalyzeTooltip: 'Analyse with AI — get a target price and recommendation',
    rowDescPlaceholderFull: 'Describe the item (condition, size, brand, flaws...) — used by AI if the listing is inaccessible',
    rowDescLabelIcon: 'Description:',

    // Transaction labels
    transactionAchat: 'Purchase',
    transactionVente: 'Sale',
    transactionAttente: 'Pending',
    transactionPerdu: 'Lost',
    transactionTooltipAchat: 'Purchase — you spent money to acquire this item',
    transactionTooltipVente: 'Sale — you sold or are listing this item for sale',
    transactionTooltipAttente: 'Pending — you are evaluating this item before deciding to buy',
    transactionTooltipPerdu: 'Lost — this pending item was sold to someone else',

    // Type labels
    typeVetement: 'Clothing',
    typeChaussures: 'Shoes',
    typeAccessoires: 'Accessories',
    typeElectronique: 'Electronics',
    typeInformatique: 'Computers',
    typeMaison: 'Home',
    typeDecoration: 'Decoration',
    typeSport: 'Sports',
    typeLoisirs: 'Hobbies',
    typeLivres: 'Books',
    typeJouets: 'Toys',
    typeCosmetique: 'Cosmetics',
    typeAlimentation: 'Food',
    typeBusiness: 'Business',
    typeAutre: 'Other',
    typeTooltipVetement: 'Clothing — clothes, coats, sweaters...',
    typeTooltipChaussures: 'Shoes — sneakers, boots, sandals...',
    typeTooltipAccessoires: 'Accessories — bags, belts, jewelry...',
    typeTooltipElectronique: 'Electronics — audio, photo, TV...',
    typeTooltipInformatique: 'Computers — computers, peripherals...',
    typeTooltipMaison: 'Home — furniture, kitchen, storage...',
    typeTooltipDecoration: 'Decoration — frames, vases, plants...',
    typeTooltipSport: 'Sports — equipment, sportswear...',
    typeTooltipLoisirs: 'Hobbies — games, instruments, collections...',
    typeTooltipLivres: 'Books — novels, comics, manuals, magazines...',
    typeTooltipJouets: 'Toys — children, figures, board games...',
    typeTooltipCosmetique: 'Cosmetics — perfumes, skincare, makeup...',
    typeTooltipAlimentation: 'Food — food products, drinks...',
    typeTooltipBusiness: 'Business — items tracked for commercial performance',
    typeTooltipAutre: 'Other — unlisted category',

    // Tutorial mock items
    tutorialItem1Title: 'iPhone 13 Pro — 256 GB',
    tutorialItem1Desc: 'Very good condition, original box, charger included.',
    tutorialItem1Reco: 'Slightly lower the price to speed up the sale.',
    tutorialItem1Insight: 'iPhone 13 Pro sells well between €420 and €500.',
    tutorialItem2Title: 'Samsung Galaxy S22 — 128 GB',
    tutorialItem2Desc: 'Refurbished grade A, battery 95%.',

    // Tutorial overlay
    tutorialLocale: { skip: 'Skip', next: 'Next', back: 'Back', close: 'Close', last: 'Finish' },
    tutorialWelcomeTitle: 'Welcome to Vintia 🎉',
    tutorialWelcomeBody: 'I will guide you through the main features. Two example items have been added to illustrate the tutorial.',
    tutorialAllTitle: 'Global view',
    tutorialAllBody: 'Click here to show all your items regardless of platform. This is your overview.',
    tutorialAddPlatTitle: 'Add a platform',
    tutorialAddPlatBody: 'Connect Vinted, Leboncoin, eBay or others to sync your sales. You can reorder them by drag and drop.',
    tutorialRecoTitle: 'AI Recommendation of the Day',
    tutorialRecoBody: 'Your AI, connected to your data, offers personalized daily advice. Click "Refresh" to regenerate the analysis.',
    tutorialStatsTitle: 'Your numbers at a glance',
    tutorialStatsBody: 'This bar summarizes your activity in real time:',
    tutorialStatsArticles: 'Items',
    tutorialStatsArticlesDesc: 'total active',
    tutorialStatsAchats: 'Purchases',
    tutorialStatsAchatsDesc: 'items bought (−)',
    tutorialStatsVentes: 'Sales',
    tutorialStatsVentesDesc: 'listed for sale (+)',
    tutorialStatsAttente: 'Pending',
    tutorialStatsAttenteDesc: 'under review',
    tutorialStatsCA: 'Revenue',
    tutorialStatsCADesc: 'revenue generated',
    tutorialStatsTotalAchats: 'Total spent',
    tutorialStatsTotalAchatsDesc: 'cumulative purchases',
    tutorialStatsMarge: 'Margin',
    tutorialStatsMargeDesc: 'Revenue − Purchases',
    tutorialPricesTitle: "An item's three prices",
    tutorialPricesAchat: 'Purchase',
    tutorialPricesAchatDesc: 'price paid to acquire the item',
    tutorialPricesPropo: 'Listed',
    tutorialPricesPropoDesc: 'price shown in your listing',
    tutorialPricesVente: 'Sold',
    tutorialPricesVenteDesc: 'price actually received at sale',
    tutorialPricesNote: 'Margin is calculated automatically: Sold − Purchase.',
    tutorialAddItemTitle: 'Add an item',
    tutorialAddItemBody: 'Click here to create a new item. An input row appears directly in the table.',
    tutorialAddItemNote: 'Fill in the title, purchase price and listed price. The more complete the form, the more precise the AI analysis.',
    tutorialIAColTitle: 'AI column',
    tutorialIAColBody: 'Shows the AI-suggested target price and a short recommendation (lower, hold, relaunch...). It fills in after an analysis on this item.',
    tutorialAnalyzeTitle: 'Market analysis',
    tutorialAnalyzeBody: 'Launches an AI analysis on this item: average market prices, demand level, trends and personalized price advice.',
    tutorialAnalyzeNote: 'Requires an API key configured in Settings.',
    tutorialReportTitle: 'Full AI report',
    tutorialReportBody: 'After an analysis, this button gives access to the detailed report: price range, popularity, presentation tips and estimated time to sell.',
    tutorialReportNote: 'The example item already has a report — try clicking it!',
    tutorialCompareTitle: 'Compare items',
    tutorialCompareBody: 'Link several items together to compare them side by side — useful for adjusting prices when you have similar items on multiple platforms.',
    tutorialCompareNote: 'The number shows how many items are linked. The two example items are already linked.',
    tutorialEditTitle: 'Edit an item',
    tutorialEditBody: 'Double-click any row or use this button to edit an item directly in the table.',
    tutorialDeleteTitle: 'Delete',
    tutorialDeleteBody: 'Delete an item after confirmation. Warning, this action is irreversible.',
    tutorialSettingsTitle: 'Settings & Profile',
    tutorialSettingsBody: 'Access your profile, configure your AI API keys and manage your preferences.',
    tutorialLogoutTitle: 'Logout',
    tutorialLogoutBody: 'Sign out of your account. Your data remains saved.',
    tutorialEndTitle: "You're ready! 🚀",
    tutorialEndBody: 'The example items have been removed. You can relaunch this tutorial at any time via the help button in the top right.',
  },
} as const;

export type Translations = typeof translations.fr;

// ── Context ────────────────────────────────────────────────────────────────
interface LanguageContextType {
  lang: Lang;
  t: Translations;
  toggleLang: () => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [lang, setLang] = useState<Lang>(() => {
    const saved = localStorage.getItem(STORAGE_KEY);
    return saved === 'en' ? 'en' : 'fr';
  });

  const toggleLang = useCallback(() => {
    setLang(prev => {
      const next: Lang = prev === 'fr' ? 'en' : 'fr';
      localStorage.setItem(STORAGE_KEY, next);
      return next;
    });
  }, []);

  const t = translations[lang] as unknown as Translations;

  return (
    <LanguageContext.Provider value={{ lang, t, toggleLang }}>
      {children}
    </LanguageContext.Provider>
  );
};

// eslint-disable-next-line react-refresh/only-export-components
export const useLang = (): LanguageContextType => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLang must be used within a LanguageProvider');
  return ctx;
};
